In [2]:
import numpy as np

# Vectors

### 1.1 Vector create

In [3]:
arr = np.array([1,2])
print(arr)

[1 2]


In [4]:
l = [1,2,3,4]
arr = np.array(l)
print(arr)

[1 2 3 4]


In [42]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
arr1 = np.arange(-2, 10)
print(arr1)

[-2 -1  0  1  2  3  4  5  6  7  8  9]


In [45]:
arr1 = np.arange(10, 10)
print(arr1)

[]


In [46]:
arr1 = np.arange(0, 10, 2)
print(arr1)

[0 2 4 6 8]


In [47]:
arr1 = np.arange(0, 10, -2)
print(arr1)

[]


In [48]:
arr1 = np.arange(10, 0, -2)
print(arr1)

[10  8  6  4  2]


### 1.2 Functions/ Features

In [5]:
l = [1,2,3,4]
arr = np.array(l)
print(arr)

[1 2 3 4]


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
print(arr.size)

4


In [8]:
print(arr.shape)

(4,)


In [40]:
# How to check vector or matrix
l = [1,2,3,4]
arr = np.array(l)
arr = arr.shape
#d = str(arr.shape)
if(len(arr) > 1):
    print('I am matrix')
else:
    print('I am vector')

I am vector


In [49]:
arr1 = np.arange(0, 10)
print(np.mean(arr1))

4.5


In [50]:
print(np.median(arr1))

4.5


In [51]:
from scipy import stats
print(stats.mode(arr1))

ModeResult(mode=array([0]), count=array([1]))


In [52]:
print(np.std(arr1))

2.8722813232690143


In [53]:
print(np.min(arr1))

0


In [54]:
print(np.max(arr1))

9


In [55]:
print(arr1 + 10)
print(arr1 - 10)
print(arr1 * 10)
print(arr1 / 10)
print(arr1 % 10)

[10 11 12 13 14 15 16 17 18 19]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]
[ 0 10 20 30 40 50 60 70 80 90]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0 1 2 3 4 5 6 7 8 9]


In [56]:
print(arr1[0])
print(arr1[-1])
print(arr1[0:6])
print(arr1[::-1])
print(arr1[::2])

0
9
[0 1 2 3 4 5]
[9 8 7 6 5 4 3 2 1 0]
[0 2 4 6 8]


In [ ]:
# Updating